package Formularios;
import javax.swing.table.DefaultTableModel;
import static Clases.Statement.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
public class Tipo_Habitacion extends javax.swing.JPanel {
    DefaultTableModel l = new DefaultTableModel();
    ResultSet r = null;
    public Tipo_Habitacion() throws SQLException {
        initComponents();
        String[] t = {"Codigo","Descripción","Estado"};
        l.setColumnIdentifiers(t);
        lista.setModel(l);
        Lista_th();
        r = getS().executeQuery("SELECT codcama FROM cama");
        while(r.next()){
            jComboBox1.addItem((String)r.getString(1));
        }
        r = getS().executeQuery("SELECT codtarifa FROM tarifa");
        while(r.next()){
            jComboBox2.addItem((String)r.getString(1));
        }
        cancelar.setVisible(false);
    }
    
    public void Lista_th() throws SQLException{
        String[] datos = new String[3];
        int f=l.getRowCount();
        if(f>0) {
            for(int i=0;i<f;i++) {
                l.removeRow(0);
            }
        }
        r = getS().executeQuery("SELECT codtipoh,descripcion,"
                            + "(CASE    WHEN estado=0 THEN 'Activo'"
                            + "         WHEN estado=1 THEN 'Inactivo'"
                            + " END)  AS estado FROM tipohabitacion");
        while(r.next()) {
            datos[0] = (String)r.getString(1);
            datos[1] = (String)r.getString(2);
            datos[2] = (String)r.getString(3);
            l.addRow(datos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Scroll = new javax.swing.JScrollPane();
        lista = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        tv = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        wifi = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        aire = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        terma = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jacuzzi = new javax.swing.JComboBox<>();
        agregar = new javax.swing.JButton();
        activo = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        Scroll.setBackground(new java.awt.Color(255, 255, 255));
        Scroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ScrollMouseReleased(evt);
            }
        });

        lista = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listaMouseReleased(evt);
            }
        });
        Scroll.setViewportView(lista);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("Descripción:");

        jLabel2.setText("Código Cama:");

        jLabel3.setText("Código Tarifa:");

        jLabel4.setText("Número de camas:");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jSpinner1.setMaximumSize(new java.awt.Dimension(10, 10));
        jSpinner1.setMinimumSize(new java.awt.Dimension(1, 1));

        jLabel5.setText("TV Cable:");

        tv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jLabel6.setText("WIFI:");

        wifi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jLabel7.setText("Aire Acondicionado:");

        aire.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jLabel8.setText("Terma:");

        terma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jLabel9.setText("Jacuzzi:");

        jacuzzi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        activo.setText("Inactivo");
        activo.setEnabled(false);
        activo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activoActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(39, 39, 39)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(88, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox1, 0, 145, Short.MAX_VALUE)
                                .addComponent(jTextField1))
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(activo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wifi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(terma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jacuzzi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel8)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(wifi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(aire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(terma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jacuzzi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar)
                    .addComponent(activo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void limpio(){
        jTextField1.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jSpinner1.setValue(1);
        tv.setSelectedIndex(0);
        wifi.setSelectedIndex(0);
        aire.setSelectedIndex(0);
        terma.setSelectedIndex(0);
        jacuzzi.setSelectedIndex(0);
        jTextField1.requestFocus();
        cod=0;
    }
    
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        if(agregar.getText().equals("Agregar")){
            if(!jTextField1.getText().equals("")&&!jComboBox1.getSelectedItem().equals("")
                &&!jComboBox2.getSelectedItem().equals("")){
                int cb=0,wi=0,ai=0,te=0,ja=0;
                if(tv.getSelectedIndex()==1){
                    cb=1;
                }
                if(wifi.getSelectedIndex()==1){
                    wi=1;
                }
                if(aire.getSelectedIndex()==1){
                    ai=1;
                }
                if(terma.getSelectedIndex()==1){
                    te=1;
                }
                if(jacuzzi.getSelectedIndex()==1){
                    ja=1;
                }
                    try {
                        getS().executeUpdate("INSERT INTO tipohabitacion(descripcion,"
                                + "codcama,codtarifa,numcama,tvcable,wifi,aireacondicionado,terma,"
                                + "jacuzzi,estado,fechreg) VALUES('"+jTextField1.getText()+"',"+jComboBox1.getSelectedItem()+","
                        +jComboBox2.getSelectedItem()+","+(Integer)jSpinner1.getValue()+","+cb+","+wi+""
                        + ","+ai+","+te+","+ja+",0,NOW())");
                        Lista_th();
                        limpio();
                    } catch (SQLException ex) {
                        Logger.getLogger(Tipo_Habitacion.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        } else if(agregar.getText().equals("Guardar")){
            int cb=0,wi=0,ai=0,te=0,ja=0;
            if(tv.getSelectedIndex()==1){
                cb=1;
            }
            if(wifi.getSelectedIndex()==1){
                wi=1;
            }
            if(aire.getSelectedIndex()==1){
                ai=1;
            }
            if(terma.getSelectedIndex()==1){
                te=1;
            }
            if(jacuzzi.getSelectedIndex()==1){
                ja=1;
            }
            try {
                getS().executeUpdate("UPDATE tipohabitacion SET descripcion='"+jTextField1.getText()+"',"
                + "codcama="+jComboBox1.getSelectedItem()+",codtarifa="+jComboBox2.getSelectedItem()+","
                        + "numcama="+(Integer)jSpinner1.getValue()+",tvcable="+cb+",wifi="+wi+","
                        + "aireacondicionado="+ai+",terma="+te+","
                        + "jacuzzi="+ja+",estado=0,fechreg=NOW() WHERE codtipoh="+cod);
                Lista_th();
                limpio();
            } catch (SQLException ex) {
                Logger.getLogger(Tipo_Habitacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_agregarActionPerformed
    private void ScrollMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScrollMouseReleased
    }//GEN-LAST:event_ScrollMouseReleased
    int cod = 0;
    private void listaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMouseReleased
        if(lista.getSelectedRow()>=0){
            int f = lista.getSelectedRow();
            cod = Integer.parseInt((String)lista.getValueAt(f,0));
            try {
                r = getS().executeQuery("SELECT descripcion,codcama,codtarifa,numcama,"
                        + "tvcable,wifi,aireacondicionado,terma,jacuzzi FROM tipohabitacion"
                        + " WHERE codtipoh="+cod);
                while(r.next()){
                    jTextField1.setText(r.getString(1));
                    jComboBox1.setSelectedItem(r.getString(2));
                    jComboBox2.setSelectedItem(r.getString(3));
                    jSpinner1.setValue(r.getInt(4));
                    tv.setSelectedIndex(r.getInt(5));
                    wifi.setSelectedIndex(r.getInt(6));
                    aire.setSelectedIndex(r.getInt(7));
                    terma.setSelectedIndex(r.getInt(8));
                    jacuzzi.setSelectedIndex(r.getInt(9));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Tipo_Habitacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            cancelar.setVisible(true);  
            activo.setEnabled(true);
            agregar.setText("Guardar");
            String estado = (String)lista.getValueAt(f,2);
            if((estado.equals("Activo"))){
                activo.setText("Inactivo");
            } else if(estado.equals("Inactivo")){
                activo.setText("Activo");
            }
        }
    }//GEN-LAST:event_listaMouseReleased

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        limpio();
        cancelar.setVisible(false);
        agregar.setText("Agregar");
        activo.setEnabled(false);
    }//GEN-LAST:event_cancelarActionPerformed

    private void activoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activoActionPerformed
        int f = lista.getSelectedRow();
        System.out.println(cod);
        if(activo.getText().equals("Activo")){
            try {
                getS().executeUpdate("UPDATE tipohabitacion SET estado=0 WHERE codtipoh="+cod);
                Lista_th();
            } catch (SQLException ex) {
                Logger.getLogger(Tipo_Habitacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if(activo.getText().equals("Inactivo")){
            try {
                getS().executeUpdate("UPDATE tipohabitacion SET estado=1 WHERE codtipoh="+cod);
                Lista_th();
            } catch (SQLException ex) {
                Logger.getLogger(Tipo_Habitacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        limpio();
        activo.setEnabled(false);
        cancelar.setVisible(false);
    }//GEN-LAST:event_activoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JButton activo;
    private javax.swing.JButton agregar;
    private javax.swing.JComboBox<String> aire;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jacuzzi;
    private javax.swing.JTable lista;
    private javax.swing.JComboBox<String> terma;
    private javax.swing.JComboBox<String> tv;
    private javax.swing.JComboBox<String> wifi;
    // End of variables declaration//GEN-END:variables
}
